# Search & Filtering Behavior
ALL_VALID: no
# Configure this as one of: all_cves, all_keywords, products
SEARCH_SCOPE: all_keywords
INCLUDE_HIGH_SEVERITY: True
HIGH_SEVERITY_THRESHOLD: 9.5

# Enable including only matched keywords if CVE is also a high CVSS score (reduce noise of low-severity CVE's)
# Disclaimer: If enabled, this means you will not see CVE's for which the CVSS score is currently blank
ENABLE_SCORE_FILTERING: True
MIN_SCORE_THRESHOLD: 6.0

# Update MITRE Exploit-DB dataset every 'n' days
MITRE_INTERVAL: 3

# If present, exclude CVE from results
EXCLUDED_KEYWORDS:
- SourceCodester

# Case-insensitive keywords in CVE Description/Summary
DESCRIPTION_KEYWORDS_I:
- auth bypass
- authentication bypass
- default credentials
- default password
- deserialization
- sql injection
- privesc
- local file inclusion
- remote file inclusion
- remote code execution
- directory traversal
- path traversal
- command injection
- access control
- file upload
- server-side request forgery
- xxe injection
- insecure
- graphql api
- server-side template injection
- request smuggling

DESCRIPTION_KEYWORDS:
- LFI
- RCE
- RFI
- SQLi
- IDOR
- SSRF
- XXE
- SSTI
- JWT
- OAuth

PRODUCT_KEYWORDS_I:
- bitrix
- 1c

PRODUCT_KEYWORDS:
- 1C
- Apache
- Bitrix
- Cisco
- Citrix
- Docker
- Drupal
- Joomla
- Grafana
- Microsoft Exchange
- Microsoft SQL
- OpenLDAP
- Python Django
- Python Flask
- Spring Boot
- Spring Core
- Spring Security
- SwaggerUI
- Tomcat
- Trend Micro
- Wordpress
